apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: demo-app
          image: demo-app:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_NAME
              value: "demo-app"
            - name: LOG_LEVEL
              value: "INFO"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: demo
spec:
  selector:
    app: demo-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP