# 1) ImagePullBackOff
apiVersion: v1
kind: Pod
metadata:
  name: demo-imagepullbackoff
  namespace: demo
spec:
  containers:
    - name: bad-image
      image: nginx:this-tag-does-not-exist
---
# 2) CrashLoopBackOff (container exits immediately)
apiVersion: v1
kind: Pod
metadata:
  name: demo-crashloop
  namespace: demo
spec:
  restartPolicy: Always
  containers:
    - name: crasher
      image: busybox
      command: ["sh", "-c", "echo 'crashing now'; exit 1"]
---
# 3) FailedScheduling (requests impossible resources)
apiVersion: v1
kind: Pod
metadata:
  name: demo-failedscheduling
  namespace: demo
spec:
  containers:
    - name: impossible
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "100"
          memory: "200Gi"
---
# 4) OOMKilled (memory limit too small + allocate more)
apiVersion: v1
kind: Pod
metadata:
  name: demo-oomkilled
  namespace: demo
spec:
  containers:
    - name: oom
      image: python:3.11-slim
      command: ["python", "-c", "a=' ' * (200*1024*1024); import time; time.sleep(3600)"]
      resources:
        limits:
          memory: "64Mi"
        requests:
          memory: "32Mi"
